Revert "fix zizmor warnings/errors"
This reverts commit bad1753fcf60b10e75850866f71db3db663029ce.

diff --git a/.github/workflows/retry-release.yaml b/.github/workflows/retry-release.yaml
--- a/.github/workflows/retry-release.yaml
+++ b/.github/workflows/retry-release.yaml
@@ -30,7 +30,6 @@ jobs:
     if: ${{ needs.apps.outputs.apps != '[]' }}
     name: Retry Release
     runs-on: ubuntu-latest
-    environment: prod
     needs:
       - apps
     strategy:
@@ -48,7 +47,7 @@ jobs:
         uses: actions/create-github-app-token@1b10c78c7865c340bc4f6099eb2f838309f1e8c3 # v3.1.1
         id: app-token
         with:
-          client-id: ${{ secrets.BOT_APP_ID }}
+          app-id: ${{ secrets.BOT_APP_ID }}
           private-key: ${{ secrets.BOT_APP_PRIVATE_KEY }}
 
       - name: Install Cosign
@@ -67,12 +66,11 @@ jobs:
         id: registry
         env:
           GITHUB_TOKEN: ${{ steps.app-token.outputs.token }}
-          APP: ${{ matrix.app }}
         run: |-
-          if ! version=$(regctl image inspect ghcr.io/${{ github.repository_owner }}/${APP}:rolling \
+          if ! version=$(regctl image inspect ghcr.io/${{ github.repository_owner }}/${{ matrix.app }}:rolling \
               | jq --raw-output '.config.Labels["org.opencontainers.image.version"]' 2>/dev/null) || [[ -z "${version}" ]];
           then
-              echo "Failed to get registry version for ${APP}"
+              echo "Failed to get registry version for ${{ matrix.app }}"
               exit 1
           fi
           echo "version=${version}" >> $GITHUB_OUTPUT
